'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TestApp.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}{\f3\fcharset0 Consolas;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;\red0\green0\blue255;\red163\green21\blue21;\red255\green0\blue0;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs19\f3\cf0 \cf0\ql{\f3 {\cf2\ltrch &lt;}{\cf3\ltrch UserControl}{\cf4\ltrch  x}{\cf2\ltrch :}{\cf4\ltrch Class}{\cf2\ltrch =&quot;CustomPanelTemplateWordCloud&quot;}\li0\ri0\sa0\sb0\fi0\ql\par}
        '''{\f3 {\ltrch              [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property CustomPanelTemplateWordCloud_XAML() As String
            Get
                Return ResourceManager.GetString("CustomPanelTemplateWordCloud_XAML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}{\f3\fcharset0 Consolas;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;\red0\green0\blue255;\red163\green21\blue21;\red255\green0\blue0;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs19\f3\cf0 \cf0\ql{\f3 {\cf2\ltrch &lt;}{\cf3\ltrch UserControl}{\cf4\ltrch  x}{\cf2\ltrch :}{\cf4\ltrch Class}{\cf2\ltrch =&quot;DictionaryTest&quot;}\li0\ri0\sa0\sb0\fi0\ql\par}
        '''{\f3 {\ltrch             }{\cf4\ltrch   [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property DictionaryTest_XAML() As String
            Get
                Return ResourceManager.GetString("DictionaryTest_XAML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}{\f3\fcharset0 Consolas;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;\red0\green0\blue255;\red43\green145\blue175;\red163\green21\blue21;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs19\f3\cf0 \cf0\ql{\f3 {\cf2\ltrch Namespace}{\ltrch  ViewModel}\li0\ri0\sa0\sb0\fi0\ql\par}
        '''{\f3 {\ltrch     }{\cf2\ltrch Public}{\ltrch  }{\cf2\ltrch Class}{\ltrch  }{\cf3\ltrch DictionaryTestViewModel [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property DictionaryTestViewModel() As String
            Get
                Return ResourceManager.GetString("DictionaryTestViewModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}{\f3\fcharset0 Consolas;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;\red0\green0\blue255;\red163\green21\blue21;\red255\green0\blue0;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs19\f3\cf0 \cf0\ql{\f3 {\cf2\ltrch &lt;}{\cf3\ltrch UserControl}{\cf4\ltrch  x}{\cf2\ltrch :}{\cf4\ltrch Class}{\cf2\ltrch =&quot;NormalTestExtended&quot;}\li0\ri0\sa0\sb0\fi0\ql\par}
        '''{\f3 {\ltrch             }{\cf4\ltr [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property NormalTestExtended_XAML() As String
            Get
                Return ResourceManager.GetString("NormalTestExtended_XAML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}{\f3\fcharset0 Consolas;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;\red0\green0\blue255;\red43\green145\blue175;\red163\green21\blue21;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs19\f3\cf0 \cf0\ql{\f3 {\cf2\ltrch Namespace}{\ltrch  ViewModel}\li0\ri0\sa0\sb0\fi0\ql\par}
        '''{\f3 {\ltrch     }{\cf2\ltrch Public}{\ltrch  }{\cf2\ltrch Class}{\ltrch  }{\cf3\ltrch NormalTestExtendedViewM [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property NormalTestExtendedViewModel() As String
            Get
                Return ResourceManager.GetString("NormalTestExtendedViewModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}{\f3\fcharset0 Consolas;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;\red0\green0\blue255;\red163\green21\blue21;\red255\green0\blue0;\red0\green128\blue0;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs19\f3\cf0 \cf0\ql{\f3 {\cf2\ltrch &lt;}{\cf3\ltrch Window}\li0\ri0\sa0\sb0\fi0\ql\par}
        '''{\f3 {\ltrch        }{\cf4\ltrch  xmlns}{\cf2\ltrch =&quot;http://schemas.microsoft.com/winfx/2006/xaml/p [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property NormalTests_XAML() As String
            Get
                Return ResourceManager.GetString("NormalTests_XAML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}{\f3\fcharset0 Consolas;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;\red0\green0\blue255;\red43\green145\blue175;\red163\green21\blue21;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs19\f3\cf0 \cf0\ql{\f3 {\cf2\ltrch Namespace}{\ltrch  ViewModel}\li0\ri0\sa0\sb0\fi0\ql\par}
        '''{\f3 {\ltrch     }{\cf2\ltrch Public}{\ltrch  }{\cf2\ltrch Class}{\ltrch  }{\cf3\ltrch NormalTestViewModel}\li [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property NormalTestViewModel() As String
            Get
                Return ResourceManager.GetString("NormalTestViewModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}{\f3\fcharset0 Consolas;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;\red0\green0\blue255;\red163\green21\blue21;\red255\green0\blue0;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs19\f3\cf0 \cf0\ql{\f3 {\cf2\ltrch &lt;}{\cf3\ltrch UserControl}{\cf4\ltrch  x}{\cf2\ltrch :}{\cf4\ltrch Class}{\cf2\ltrch =&quot;PersonItemTemplateTest&quot;}\li0\ri0\sa0\sb0\fi0\ql\par}
        '''{\f3 {\ltrch             }{\cf4 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property PersonItemTemplateTest_XAML() As String
            Get
                Return ResourceManager.GetString("PersonItemTemplateTest_XAML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}{\f3\fcharset0 Consolas;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;\red0\green0\blue255;\red43\green145\blue175;\red163\green21\blue21;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs19\f3\cf0 \cf0\ql{\f3 {\cf2\ltrch Imports}{\ltrch  System.Collections.ObjectModel}\li0\ri0\sa0\sb0\fi0\ql\par}
        '''{\f3 \li0\ri0\sa0\sb0\fi0\ql\par}
        '''{\f3 {\cf2\ltrch Namespace}{\ltrch  ViewModel}\li0\ri0\s [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property PersonItemTemplateViewModel() As String
            Get
                Return ResourceManager.GetString("PersonItemTemplateViewModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}{\f3\fcharset0 Consolas;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;\red0\green0\blue255;\red43\green145\blue175;\red163\green21\blue21;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs19\f3\cf0 \cf0\ql{\f3 {\cf2\ltrch Imports}{\ltrch  AutoInsertPopup}\li0\ri0\sa0\sb0\fi0\ql\par}
        '''{\f3 \li0\ri0\sa0\sb0\fi0\ql\par}
        '''{\f3 {\cf2\ltrch Namespace}{\ltrch  ViewModel}\li0\ri0\sa0\sb0\fi0\ql\p [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property PersonsWithCustomHeaderViewModel() As String
            Get
                Return ResourceManager.GetString("PersonsWithCustomHeaderViewModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}{\f3\fcharset0 Consolas;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;\red0\green0\blue255;\red43\green145\blue175;\red163\green21\blue21;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs19\f3\cf0 \cf0\ql{\f3 {\cf2\ltrch Namespace}{\ltrch  ViewModel}\li0\ri0\sa0\sb0\fi0\ql\par}
        '''{\f3 {\ltrch     }{\cf2\ltrch Public}{\ltrch  }{\cf2\ltrch Class}{\ltrch  }{\cf3\ltrch PersonViewModel}\li0\ri [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property PersonViewModel() As String
            Get
                Return ResourceManager.GetString("PersonViewModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}{\f3\fcharset0 Consolas;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;\red0\green0\blue255;\red163\green21\blue21;\red255\green0\blue0;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs19\f3\cf0 \cf0\ql{\f3 {\cf2\ltrch &lt;}{\cf3\ltrch UserControl}{\cf4\ltrch  x}{\cf2\ltrch :}{\cf4\ltrch Class}{\cf2\ltrch =&quot;CustomHeaderTemplateTest&quot;}\li0\ri0\sa0\sb0\fi0\ql\par}
        '''{\f3 {\ltrch             }{\c [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property PersonWithCustomHeader_XAML() As String
            Get
                Return ResourceManager.GetString("PersonWithCustomHeader_XAML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}{\f3\fcharset0 Consolas;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;\red0\green0\blue255;\red43\green145\blue175;\red163\green21\blue21;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs19\f3\cf0 \cf0\ql{\f3 {\cf2\ltrch Imports}{\ltrch  System.Collections.ObjectModel}\li0\ri0\sa0\sb0\fi0\ql\par}
        '''{\f3 \li0\ri0\sa0\sb0\fi0\ql\par}
        '''{\f3 {\cf2\ltrch Namespace}{\ltrch  ViewModel}\li0\ri0\s [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property PersonWithCustomHeaderViewModel() As String
            Get
                Return ResourceManager.GetString("PersonWithCustomHeaderViewModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}{\f3\fcharset0 Consolas;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;\red0\green0\blue255;\red43\green145\blue175;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs19\f3\cf0 \cf0\ql{\f3 {\cf2\ltrch Public}{\ltrch  }{\cf2\ltrch Class}{\ltrch  }{\cf3\ltrch WordCloudItem}\li0\ri0\sa0\sb0\fi0\ql\par}
        '''{\f3 {\ltrch         }{\cf2\ltrch Public}{\ltrch  }{\cf2\ltrch Property}{\ltrch  Caption }{ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property WordCloudItem() As String
            Get
                Return ResourceManager.GetString("WordCloudItem", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
