'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class MySettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
    
#Region "Automatische My.Settings-Speicherfunktion"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As MySettings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("{\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman"& _ 
        ";}{\f2\fcharset0 Segoe UI;}{\f3\fcharset0 Consolas;}}{\colortbl\red0\green0\blue"& _ 
        "0;\red255\green255\blue255;\red0\green0\blue255;\red163\green21\blue21;\red255\g"& _ 
        "reen0\blue0;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs18\f2\cf0 \cf0\"& _ 
        "ql{\fs19\f3 {\ltrch  }{\cf2\ltrch <}{\cf3\ltrch AutoInsertPopup}{\cf2\ltrch :}{\"& _ 
        "cf3\ltrch AutoInsertPopupControl}{\cf4\ltrch  x}{\cf2\ltrch :}{\cf4\ltrch Name}{"& _ 
        "\cf2\ltrch =""pop1""}{\cf4\ltrch  TargetControl}{\cf2\ltrch =""\{}{\cf3\ltrch Bindi"& _ 
        "ng}{\cf4\ltrch  ElementName}{\cf2\ltrch =txtTest1\}""}{\cf4\ltrch  OpenOnTargetFo"& _ 
        "cused}{\cf2\ltrch =""True""}\li0\ri0\sa0\sb0\fi0\ql\par}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"{\fs19\f3 {\ltrch       "& _ 
        "                                         }{\cf4\ltrch  AutoInsertList}{\cf2\ltrc"& _ 
        "h =""\{}{\cf3\ltrch Binding}{\cf4\ltrch  TestList}{\cf2\ltrch \}""}{\cf4\ltrch  Op"& _ 
        "enPopupTriggerChar}{\cf2\ltrch =""#""}{\cf4\ltrch  ReplaceTriggerChar}{\cf2\ltrch "& _ 
        "=""True""}\li0\ri0\sa0\sb0\fi0\ql\par}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"{\fs19\f3 {\ltrch                         "& _ 
        "                       }{\cf4\ltrch  VerticalOffset}{\cf2\ltrch =""\{}{\cf3\ltrch"& _ 
        " Binding}{\cf4\ltrch  ElementName}{\cf2\ltrch =txtTest1,}{\cf4\ltrch  Path}{\cf2"& _ 
        "\ltrch =ActualHeight\}""/>}\li0\ri0\sa0\sb0\fi0\ql\par}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"{\fs24\f2 {\ltrch }\li0\"& _ 
        "ri0\sa0\sb0\fi0\ql\par}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"}")>  _
    Public Property NormalTestXaml() As String
        Get
            Return CType(Me("NormalTestXaml"),String)
        End Get
        Set
            Me("NormalTestXaml") = value
        End Set
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.TestApp.MySettings
            Get
                Return Global.TestApp.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
